# Generated by ModEngineering. Edit mod.json or the shared implementation.
& python "$PSScriptRoot/../shared/ModEngineering/scripts/mod.py" build --repo "$PSScriptRoot/.." @args
if ($LASTEXITCODE -ne 0) { throw "ModEngineering build failed ($LASTEXITCODE)." }
