# Generated by ModEngineering. Edit mod.json or the shared implementation.
& python "$PSScriptRoot/../shared/ModEngineering/scripts/mod.py" check --repo "$PSScriptRoot/.." @args
if ($LASTEXITCODE -ne 0) { throw "ModEngineering check failed ($LASTEXITCODE)." }
