# Generated by ModEngineering. Edit mod.json or the shared implementation.
& python "$PSScriptRoot/../shared/ModEngineering/scripts/mod.py" test --repo "$PSScriptRoot/.." @args
if ($LASTEXITCODE -ne 0) { throw "ModEngineering test failed ($LASTEXITCODE)." }
